---
title: "Modelling Zeno"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(forcats)
library(broom)
library(caTools)
library(caret)
may <- read_csv("AP-Survey/may_happiness.csv")
april <- read_csv("AP-Survey/april_happiness.csv")
```


Deleting variables relating to SOC5 to prevent data leakage:
```{r delete-SOC5-answers-may}
may <- may %>%
    select(- c(SOC5A, SOC5B, SOC5C, SOC5D, SOC5E))
```
```{r delete-SOC5-answers-april}
april <- april %>%
    select(- c(SOC5A, SOC5B, SOC5C, SOC5D, SOC5E))
head(april)
```

```{r factor-SOC1}
may$SOC1 <- factor(may$SOC1, levels = c("All", "Most", "Some", "None"), ordered = TRUE)
april$SOC1 <- factor(april$SOC1, levels = c("All", "Most", "Some", "None"), ordered = TRUE)
```

```{r factor-all-SOCs}
soc_cols = c("SOC2A", "SOC2B", "SOC3A", "SOC3B")
may[soc_cols] = lapply (may[soc_cols], factor, ordered = FALSE)
april[soc_cols] = lapply (april[soc_cols], factor, ordered = FALSE)
```

```{r factor-yes-no-questions}

colvars = names(may)


start_loc = match("ECON8A",colvars)


end_loc = match("ECON8S",colvars)


may[start_loc:end_loc] = lapply(may[start_loc:end_loc], factor, ordered = FALSE)

april[start_loc:end_loc] = lapply(april[start_loc:end_loc], factor, ordered = FALSE)

yesnocols = c("SOC4A", "SOC4B", "PHYS4", "PHYS5", "PHYS6")
may[yesnocols] = lapply(may[yesnocols], factor)
april[yesnocols] = lapply(april[yesnocols], factor)

start_loc2 = match("PHYS1A",colvars)


end_loc2 = match("PHYS1Q",colvars)


may[start_loc2:end_loc2] = lapply(may[start_loc2:end_loc2], factor, ordered = FALSE)

april[start_loc2:end_loc2] = lapply(april[start_loc2:end_loc2], factor, ordered = FALSE)

yesnocols2 = c("PHYS11", "PHYS9A", "PHYS9B", "PHYS9C", "PHYS9D", "PHYS9E", "PHYS9F", "PHYS9G", "PHYS9H")
may[yesnocols2] = lapply (may[yesnocols2], factor)
april[yesnocols2] = lapply (april[yesnocols2], factor)
```

``` {r recode-PHYS8}
may$PHYS8 <- factor(may$PHYS8)
april$PHYS8 <- factor(april$PHYS8)
```

``` {r recode-likely}
probcols = c("PHYS8", "PHYS10A", "PHYS10B", "PHYS10C", "PHYS10D", "PHYS10E", "ECON4A", "ECON4B")
may[probcols] = lapply(may[probcols],factor)
april[probcols] = lapply(april[probcols],factor)
```

``` {r recode-PHYS2}
start_loc3 = match("PHYS2_1",colvars)


end_loc3 = match("PHYS2_REF",colvars)


may[start_loc3:end_loc3] = lapply(may[start_loc3:end_loc3], factor, ordered = FALSE)

april[start_loc3:end_loc3] = lapply(april[start_loc3:end_loc3], factor, ordered = FALSE)
```

```{r recode-ECON7}
start_loc4 = match("ECON7_1",colvars)


end_loc4 = match("ECON7_REF",colvars)


may[start_loc4:end_loc4] = lapply(may[start_loc4:end_loc4], factor, ordered = FALSE)

april[start_loc4:end_loc4] = lapply(april[start_loc4:end_loc4], factor, ordered = FALSE)

cols = c("ECON1", "ECON4")
april[cols] = lapply(april[cols], factor, ordered = FALSE)
may[cols] = lapply(may[cols], factor, ordered = FALSE)
#I messed up and had to convert ECON2 back to numerical
april$ECON2 = as.numeric(april$ECON2)
```

``` {r recode-a-huge-chunk}
start_loc5 = match("ECON6A",colvars)


end_loc5 = match("PHYS6",colvars)


may[start_loc5:end_loc5] = lapply(may[start_loc5:end_loc5], factor, ordered = FALSE)

april[start_loc5:end_loc5] = lapply(april[start_loc5:end_loc5], factor, ordered = FALSE)

#convert back to numerical
april$PHYS11_TEMP = as.numeric(april$PHYS11_TEMP)
may$PHYS11_TEMP = as.numeric(may$PHYS11_TEMP)
may$HH01S = as.numeric(may$HH01S)
may$HH25S = as.numeric(may$HH25S)
may$HH612S = as.numeric(may$HH612S)
may$HH1317S = as.numeric(may$HH1317S)
may$HH18OVS = as.numeric(may$HH18OVS)

ordered_cols = c("EDUCATION", "HHSIZE1","HHINCOME", "AGE4", "AGE7", "EDUC4", "INC_BANNER", "AGE_BANNER", "HH_BANNER", "P_DENSE")
may[ordered_cols] = lapply(may[ordered_cols], factor, ordered = TRUE)
april[ordered_cols] = lapply(april[ordered_cols], factor, ordered = TRUE)

unordered_cols = c("GENDER", "RACE1_BANNER","RACE2_BANNER", "RACETH", "RACE_R2", "LANGUAGE", "REGION4", "REGION9")
may[unordered_cols] = lapply(may[unordered_cols], factor, ordered = FALSE)
april[unordered_cols] = lapply(april[unordered_cols], factor, ordered = FALSE)
```

```{r train-test-split}
april <- april %>%
  filter_all(all_vars(. != "(98) SKIPPED ON WEB")) %>%
  filter_all(all_vars(. != "(99) REFUSE")) %>%
  filter_all(all_vars(. != "(77) DON'T KNOW")) %>%
  filter_all(all_vars(. != "DON'T KNOW")) %>%
  filter_all(all_vars(. != "(99) REFUSED")) %>%
  filter_all(all_vars(. != "(77) Not sure")) %>%
  filter_all(all_vars(. != "(2) Applied for")) %>%
  filter_all(all_vars(. != "(2) Applied")) %>%
  filter_all(all_vars(. != "SKIPPED ON WEB")) %>%
  filter_all(all_vars(. != "REFUSE")) %>%
  filter_all(all_vars(. != "(88) Removed for disclosure risk")) %>%
  filter_all(all_vars(. != "REFUSED"))
may <- may %>%
  filter_all(all_vars(. != "(98) SKIPPED ON WEB")) %>%
  filter_all(all_vars(. != "(99) REFUSE")) %>%
  filter_all(all_vars(. != "(77) DON'T KNOW")) %>%
  filter_all(all_vars(. != "DON'T KNOW")) %>%
  filter_all(all_vars(. != "(99) REFUSED")) %>%
  filter_all(all_vars(. != "(77) Not sure")) %>%
  filter_all(all_vars(. != "(2) Applied for")) %>%
  filter_all(all_vars(. != "(2) Applied")) %>%
  filter_all(all_vars(. != "SKIPPED ON WEB")) %>%
  filter_all(all_vars(. != "REFUSE")) %>%
  filter_all(all_vars(. != "(88) Removed for disclosure risk")) %>%
  filter_all(all_vars(. != "REFUSED"))

	may <- may %>% mutate(ECON2fac = as.factor(case_when(
  0 <= as.numeric(ECON2) & as.numeric(ECON2) < 25 ~ "0 to 25h",
  25 <= as.numeric(ECON2) & as.numeric(ECON2) < 40 ~ "25 to 40h",
  40 <= as.numeric(ECON2) & as.numeric(ECON2) < 60 ~ "40 to 60h",
  60 <= as.numeric(ECON2) & as.numeric(ECON2) ~ "60h+",
  TRUE ~ "No Info provided"
)))
april <- april %>% mutate(ECON2fac = as.factor(case_when(
  0 <= as.numeric(ECON2) & as.numeric(ECON2) < 25 ~ "0 to 25h",
  25 <= as.numeric(ECON2) & as.numeric(ECON2) < 40 ~ "25 to 40h",
  40 <= as.numeric(ECON2) & as.numeric(ECON2) < 60 ~ "40 to 60h",
  60 <= as.numeric(ECON2) & as.numeric(ECON2) ~ "60h+",
  TRUE ~ "No Info provided"
)))
```

``` {r split}
require(caTools)
may_NN <- na.omit(may)
april_NN <- na.omit(april)

set.seed(121)
sample <- sample.split(may$HHINCOME, SplitRatio = 0.75)
trainmay <- subset(may, sample == TRUE)
testmay <- subset(may, sample == FALSE)
set.seed(101)
sample <- sample.split(april$happiness, SplitRatio = 0.75)
trainapril <- subset(april, sample == TRUE)
testapril <- subset(april, sample == FALSE)
set.seed(99)
sample <- sample.split(may_NN$happiness, SplitRatio = 0.75)
trainmay_NN <- subset(may_NN, sample == TRUE)
testmay_NN <- subset(may_NN, sample == FALSE)
set.seed(96)
sample <- sample.split(april_NN, SplitRatio = 0.75)
trainapril_NN <- subset(april_NN, sample == TRUE)
testapril_NN <- subset(april_NN, sample == FALSE)
```

``` {r firstmodels}
# try predicting the happiness based on social interactions and income
soc_int <- lm(happiness ~ HHINCOME + SOC3A, trainmay)
predictions_socint = predict(soc_int, testmay)
RMSE(testmay$happiness, predictions_socint, na.rm = TRUE)
summary(soc_int)$adj.r.squared
summary(soc_int)$r.squared
```

````{r key-demographic-features-vs-happiness}
# This is already quite a bit better!
dem_feat = lm(happiness ~ AGE_BANNER + HHINCOME + RACE1_BANNER + GENDER + EDUCATION, trainmay)
testmaymod <- testmay %>%
  filter(AGE_BANNER != "(88) Removed for disclosure risk")
predictions_demfeat = predict(dem_feat, testmaymod)
RMSE(testmaymod$happiness, predictions_demfeat, na.rm = TRUE)
summary(dem_feat)$adj.r.squared
summary(dem_feat)$r.squared
tidy(dem_feat)
```

``` {r health-and-econ-combined}
#health factors improve the model quite a bit, next step would be to combine it with economic data
health <- lm(happiness ~ PHYS9A + PHYS9B + PHYS9C + PHYS9D + PHYS9E + PHYS9F + PHYS9G + PHYS9H + PHYS3A + PHYS3B + PHYS3C + PHYS3D + PHYS3E + PHYS3F + PHYS3G + PHYS3H + PHYS3I + PHYS3J + PHYS3K + PHYS3L + PHYS3M + PHYS4 + PHYS8 + PHYS1A + PHYS1B + PHYS1C + PHYS1D + PHYS1E + PHYS1F + PHYS1G + PHYS1H + PHYS1I + PHYS1J + PHYS1K + PHYS1L + PHYS1M + PHYS1N + PHYS1O + PHYS1P + PHYS1Q + PHYS5 + PHYS6 + PHYS11 + PHYS10A + PHYS10B + PHYS10C + PHYS10D + PHYS10E + PHYS7_1 + PHYS7_2 + PHYS7_3 + PHYS7_4 + PHYS7_SKP + PHYS2_1 + PHYS2_2 + PHYS2_3 + PHYS2_4 + PHYS2_5 + PHYS2_6 + PHYS2_7 + PHYS2_8 + PHYS2_9 + PHYS2_10 + PHYS2_11 + PHYS2_12 + PHYS2_13 + PHYS2_14 + PHYS2_15 + PHYS2_16 + PHYS2_17 + PHYS2_18 + PHYS2_DK + PHYS2_SKP, trainmay)
testmaymod2 <- testmay %>%
  filter(PHYS3A != "(99) REFUSED" & PHYS8 != "(77) DON'T KNOW")
predictions_health = predict(health, testmaymod2)
RMSE(testmaymod2$happiness, predictions_health, na.rm = TRUE)
summary(health)$adj.r.squared
summary(health)$r.squared
tidy(health)
```

``` {r how-about-healthecon-factors?, eval = FALSE}
#health and econ
healthecon <- lm(happiness ~ PHYS9A + PHYS9B + PHYS9C + PHYS9D + PHYS9E + PHYS9F + PHYS9G + PHYS9H + PHYS3A + PHYS3B + PHYS3C + PHYS3D + PHYS3E + PHYS3F + PHYS3G + PHYS3H + PHYS3I + PHYS3J + PHYS3K + PHYS3L + PHYS3M + PHYS4 + PHYS8 + PHYS1A + PHYS1B + PHYS1C + PHYS1D + PHYS1E + PHYS1F + PHYS1G + PHYS1H + PHYS1I + PHYS1J + PHYS1K + PHYS1L + PHYS1M + PHYS1N + PHYS1O + PHYS1P + PHYS1Q + PHYS5 + PHYS6 + PHYS11 + PHYS10A + PHYS10B + PHYS10C + PHYS10D + PHYS10E + PHYS7_1 + PHYS7_2 + PHYS7_3 + PHYS7_4 + PHYS7_SKP + PHYS2_1 + PHYS2_2 + PHYS2_3 + PHYS2_4 + PHYS2_5 + PHYS2_6 + PHYS2_7 + PHYS2_8 + PHYS2_9 + PHYS2_10 + PHYS2_11 + PHYS2_12 + PHYS2_13 + PHYS2_14 + PHYS2_15 + PHYS2_16 + PHYS2_17 + PHYS2_18 + PHYS2_DK + PHYS2_SKP  + HHINCOME + ECON1 + HHINCOME + ECON4A + ECON4B, trainmay)
testmaymod2 <- testmay %>%
  filter(PHYS3A != "(99) REFUSED" & PHYS8 != "(77) DON'T KNOW")
predictions_healthecon = predict(healthecon, testmaymod2)
RMSE(testmaymod2$happiness, predictions_healthecon, na.rm = TRUE)
mean(testmaymod2$happiness - predictions_healthecon, na.rm = TRUE)
summary(healthecon)$adj.r.squared
summary(healthecon)$r.squared
tidy(healthecon)
```

``` {r econ-factors}
econ <- lm(happiness ~ ECON8A + ECON8B + ECON8C + ECON8D +  ECON8E + ECON8F + ECON8G + ECON8H +  ECON8I + ECON8J + ECON8K + ECON8L +  ECON8M + ECON8N + ECON8O + ECON8P + ECON8Q + ECON8R + ECON8S + ECON7_1 + ECON7_2 + ECON7_3 + ECON7_4 +  ECON7_5 + ECON7_6 + ECON7_7 + ECON7_8 +  ECON7_DK + ECON7_SKP + ECON7_REF + ECON1 + ECON3 + ECON4A + ECON4B , trainmay)
```